# Generated by Django 4.2.18 on 2025-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_make_pan_number_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingdetails',
            name='razorpay_contact_id',
        ),
        migrations.RemoveField(
            model_name='bankingdetails',
            name='razorpay_fund_account_id',
        ),
        migrations.AlterField(
            model_name='bankingdetails',
            name='contact_type',
            field=models.CharField(help_text='e.g. Savings, Current, etc.', max_length=20),
        ),
    ]
