# Generated by Django 4.2.18 on 2025-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_bankingdetails_razorpay_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/profile_pic'),
        ),
    ]
