# Generated by Django 4.2.18 on 2025-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/pic.png', null=True, upload_to='uploads/profile_pic'),
        ),
    ]
