# Generated by Django 4.2.18 on 2025-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_mobilebanner_options_alter_webbanner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be used for MLM commission distribution', max_digits=10),
        ),
    ]
