# Generated by Django 4.2.18 on 2025-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_special_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products'),
        ),
    ]
