# Generated by Django 4.2.18 on 2025-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, default='default/product.png', null=True, upload_to='uploads/products'),
        ),
    ]
