# Generated by Django 4.2.18 on 2025-11-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_proof_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
