# Generated by Django 4.2.18 on 2025-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_confirmed_at_payment_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
