# Generated by Django 4.2.18 on 2025-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
