# Generated by Django 4.2.18 on 2025-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_payout_fee_payout_final_amount_payout_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='razorpay_payout_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payout',
            name='confirmation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payout_screenshots/'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
