# Generated by Django 4.2.18 on 2025-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_payout_razorpay_payout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
